apiVersion: v1
kind: Pod
metadata:
  name: sample-webapp
  labels:
    name: sample-webapp
spec:
  containers:
  - name: sample-webapp
    image: nginx 
    volumeMounts: 
      - name: shared-logs
        mountPath: /var/log/nginx
  - name: sidecar-container
    image: busybox
    command: ["sh","-c","while true; do cat /var/log/nginx/access.log; sleep 30; done"]
    volumeMounts:
      - name: shared-logs
        mountPath: /var/log/nginx
  volumes: 
    - name: shared-logs
      emptyDir: {}