--- 
kind: Namespace
apiVersion: v1
metadata:
  name: roboshop-ns
  labels:
    name: roboshop

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: roboshop-ns
  name: roboshop-admin-role
rules:
- apiGroups: ["*"] # "" indicates the core API group
  resources: ["*"] # STAR means all
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: roboshop-admin-rolebinding
  namespace: roboshop-ns
subjects:
- kind: roboshop-user
  name: jane 
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role 
  name: roboshop-admin-role 
  apiGroup: rbac.authorization.k8s.io