---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-sc
provisioner: ebs.csi.aws.com
reclaimPolicy: Retain
allowVolumeExpansion: true 
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: gp2

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-ebs-dynamic-pvc
spec:
  storageClassName: ebs-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
  

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-for-PV
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-container
          image: nginx
          volumeMounts:
            - name: my-volume
              mountPath: /usr/share/nginx/html
      volumes:
        - name: my-volume
          persistentVolumeClaim:
            claimName: my-ebs-dynamic-pvc
