# kubectl get rs
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx
  labels: # replica set labels
    app: Nginx
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels: # This syntax gonna identify the which pods should scale and manage. 
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: nginxrep
        image: nginx:alpine 